//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::activity_data::Entity as ActivityData;
pub use super::project::Entity as Project;
pub use super::section::Entity as Section;
pub use super::sub_task::Entity as SubTask;
pub use super::task::Entity as Task;
pub use super::window_activity_data::Entity as WindowActivityData;
